In [2]:
import numpy as np

In [4]:
#q1
#a)
arr=np.array([1,2,3,6,4,5])
arr2=np.flip(arr)
print(arr2)

[5 4 6 3 2 1]


In [6]:
#b)
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flat_1=array1.flatten()
flat_2=array1.ravel()
print(flat_1)
print(flat_2)

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


In [9]:
#c)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
comp=np.array_equal(arr1,arr2)
print(comp)

True


In [11]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
values, counts = np.unique(x, return_counts=True)
most_freq_value = values[np.argmax(counts)]
indices_x = np.where(x == most_freq_value)

print(most_freq_value) 
print(indices_x)

1
(array([0, 5, 7, 8, 9], dtype=int64),)


In [13]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
sum_all = np.sum(gfg)
sum_row = np.sum(gfg, axis=1)
sum_col = np.sum(gfg, axis=0)
print(sum_all)
print(sum_row) 
print(sum_col)

45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [15]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
diag_sum = np.trace(n_array)
eig_vals, eig_vecs = np.linalg.eig(n_array)
inverse_matrix = np.linalg.inv(n_array)
determinant = np.linalg.det(n_array)
print("Diagonal sum:", diag_sum)
print("Eigenvalues:", eig_vals)
print("Eigenvectors:\n", eig_vecs)
print("Inverse:\n", inverse_matrix)
print("Determinant:", determinant)

Diagonal sum: 176
Eigenvalues: [98.16835147 28.097044   49.73460452]
Eigenvectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant: 137180.0000000001


In [17]:
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
mul1 = np.dot(p, q)
cov1 = np.cov(p.T, q.T)
print("Multiplication (i):\n", mul1)
print("Covariance (i):\n", cov1)

Multiplication (i):
 [[16 19]
 [26 31]]
Covariance (i):
 [[0.5 0.5 1.  1. ]
 [0.5 0.5 1.  1. ]
 [1.  1.  2.  2. ]
 [1.  1.  2.  2. ]]


In [21]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
inner_prod = np.inner(x, y)
outer_prod = np.outer(x, y)
cartesian_prod = np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2)
print("Inner:\n", inner_prod)
print("\nOuter:\n", outer_prod)
print("\nCartesian:\n", cartesian_prod)

Inner:
 [[17 52]
 [13 62]]

Outer:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]

Cartesian:
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [22]:
#Q2
array = np.array([[1, -2, 3], [-4, 5, -6]])
abs_val = np.abs(array)
flat = array.flatten()
p_flat = np.percentile(flat, [25, 50, 75])
p_col = np.percentile(array, [25, 50, 75], axis=0)
p_row = np.percentile(array, [25, 50, 75], axis=1)
mean_flat, median_flat, std_flat = np.mean(flat), np.median(flat), np.std(flat)
mean_col, median_col, std_col = np.mean(array, axis=0), np.median(array, axis=0), np.std(array, axis=0)
mean_row, median_row, std_row = np.mean(array, axis=1), np.median(array, axis=1), np.std(array, axis=1)
print("Absolute:\n", abs_val)
print("Percentiles flat:", p_flat)
print("Percentiles col:\n", p_col)
print("Percentiles row:\n", p_row)
print("Mean flat:", mean_flat, "Median flat:", median_flat, "Std flat:", std_flat)


Absolute:
 [[1 2 3]
 [4 5 6]]
Percentiles flat: [-3.5 -0.5  2.5]
Percentiles col:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles row:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Mean flat: -0.5 Median flat: -0.5 Std flat: 3.8622100754188224


In [23]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
floor_val = np.floor(a)
ceil_val = np.ceil(a)
trunc_val = np.trunc(a)
round_val = np.round(a)
print("Floor:", floor_val)
print("Ceiling:", ceil_val)
print("Truncate:", trunc_val)
print("Round:", round_val)

Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling: [-1. -1. -0.  1.  2.  2.  3.]
Truncate: [-1. -1. -0.  0.  1.  1.  3.]
Round: [-2. -2. -0.  0.  2.  2.  3.]


In [24]:
#q3
arr = np.array([10, 52, 62, 16, 16, 54, 453])
sorted_arr = np.sort(arr)
indices_sorted = np.argsort(arr)
smallest4 = np.sort(arr)[:4]
largest5 = np.sort(arr)[-5:]
print("Sorted:", sorted_arr)
print("Indices:", indices_sorted)
print("4 smallest:", smallest4)
print("5 largest:", largest5)

Sorted: [ 10  16  16  52  54  62 453]
Indices: [0 3 4 1 5 2 6]
4 smallest: [10 16 16 52]
5 largest: [ 16  52  54  62 453]


In [25]:
arr2 = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integer_elements = arr2[arr2 == np.floor(arr2)]
float_elements = arr2[arr2 != np.floor(arr2)]
print("Integers:", integer_elements)
print("Floats:", float_elements)

Integers: [1. 2. 3. 2.]
Floats: [1.2 2.2]
